### ISSUE TITLE
Doesn't start when installed as a dependency

### ISSUE THREAD

**Issue by forivall** [StreetStrider/repl.js#5]
When installed as a (dev) dependency, installed with npm 3 (or 2 + deduping), the repl doesn't start.
```
» node_modules/.bin/repl.js 
module.js:442
    throw err;
    ^

Error: Cannot find module '/Users/jordanklassen/Code/example/node_modules/repl.js/src/req/../../node_modules/aux.js/object/extend'
    at Function.Module._resolveFilename (module.js:440:15)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.req.local (/Users/jordanklassen/Code/example/node_modules/repl.js/src/req/req.js:8:9)
    at Object.<anonymous> (/Users/jordanklassen/Code/example/node_modules/repl.js/src/repl.js:13:17)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```
```
{ example: '1.0.0',
  npm: '3.8.9',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.2.0',
  openssl: '1.0.2h',
  uv: '1.9.1',
  v8: '5.0.71.47',
  zlib: '1.2.8' }
```

**Comment by StreetStrider** [comment]
@forivall, thanks, I'll start with reproducing.

**Comment by StreetStrider** [comment]
@forivall, can you try `master`?

**Comment by forivall** [comment]
Works! 👍 
```
» npm i StreetStrider/repl.js
example@1.0.0 /Users/jordanklassen/Code/example
└─┬ repl.js@2.3.4  (git://github.com/streetstrider/repl.js.git#eca503e9cf00cd55032fa91e785601247ac1d873)
```

**Comment by StreetStrider** [comment]
`+ repl.js@2.3.5`
